services:
  calibrate_shaper:
    image: mkuf/klipper:latest-mcu
    privileged: true
    entrypoint: python3 /opt/klipper/scripts/calibrate_shaper.py
    working_dir: /opt/resonances
    volumes:
      - ${INSTALLDIR}/klipper/resonances:/opt/resonances
